sleuth-io/terraform-provider-sleuth

CHANGELOG.md, internal/gqlclient/models.go, internal/provider/resource_project.go, main.go
Project description serves no purpose anymore, we have removed it from the web application. Marking as deprecated in the provider in order to enable removal of the field in the next major release.
=> Mark project description as deprecated

.github/workflows/release.yml, docs/resources/code_change_source.md, internal/provider/resource_code_change_source.go
This is the information that users can get from inspecting the [GraphQL schema](https://app.sleuth.io/graphql) `DeployTrackingType`, but it's nicer to have that clearly documented in the provider docs themselves.
=> Document valid deployment tracking type options

docs/index.md, internal/gqlclient/models.go, internal/provider/resource_code_change_source.go
Warning: I didn't run this except for `make build`. I believe this should correctly add support for given field as described in Linear issue.
I don't know what else has to be done here – will merge to `main` auto release new version or one has to do so manually with `make release`?
Best reviewed with [hidden white space in diff](https://github.com/sleuth-io/terraform-provider-sleuth/pull/66/files?diff=unified&w=1).
=> SD-7531: Update code change source client to include `matchBranchToEnvironment`

examples/resources/sleuth_code_change_source/resource.tf, internal/provider/resource_code_change_source.go, templates/contributing/README.md.tmpl
Documentation is autogenerated and for a few updates, we have added it directly into the resulting files. This causes issues when we try to autogenerate docs again causing us to loose already written docs. This PR adds losing data in correct places so autogenerating works again.
=> BROC-305: Update documentation at source to correctly autogenerate it

CHANGELOG.md, docs/contributing/README.md, docs/resources/code_change_source.md, internal/gqlclient/code_change_sources.go, internal/provider/resource_code_change_source.go
We were updating env slugs on the fly - this causes issues when terraform tries to re-calcualate the plan for change.
There is no clear or nice way to remove the plan because SDK calls DiffSuppressFunc on individual values not on whole plan as one.
Current resolution is to introduce id field that is composed of our calculated slug and leave slug as-is to avoid un-necessary changes.
To test:
- Go to master & install provider
- apply `sleuth_code_change_source` with `environment_mapping`
- after successful apply - try to plan/apply again - see changes in `env_mapping`
- switch to this branch and install provider
- try to plan/apply - observe no changes in `env_mapping`
Resolves: https://github.com/sleuth-io/terraform-provider-sleuth/issues/58
=> BROC-205: environment slug always showing as updating in tf plan

Makefile
We shouldn't make assumptions about what developer's OS and architecture
are and ask them to change as needed. We can get them from the
environment at runtime.
=> BROC-383: Get OS and arch from environment

CHANGELOG.md, docs/resources/incident_impact_source.md, examples/resources/sleuth_incident_impact_source/resource.tf, internal/gqlclient/models.go, internal/provider/resource_incident_impact_source.go
We have an incident impact source resource, but Blameless is not currently a supported provider. This commit will add Blameless as a supported provider.
=> BROC-488: Add Blameless as provider

internal/gqlclient/environments.go, internal/provider/provider.go, internal/sleuth/environment_resource.go, internal/sleuth/project_resource.go, internal/sleuth/provider.go
Rewrite existing environment resources using Framework SDK.
Note:
this does not fix the old bug when we can't delete the default env. There is no quick fix around that so what was done was to expose data out nicer so they at least get some back telling them that something is wrong.
=> BROC-262: Rewrite environment resource using Framework SDK

internal/sleuth/error_impact_source_resource_test.go
Add error impact source acceptance tests. Will be on hold until env resource is merged
=> BROC-520: Add error impact source acceptance tests

.github/workflows/test.yml, internal/sleuth/code_change_source_resource.go, internal/sleuth/code_change_source_resource_test.go
Add acceptance tests for Code Change Source
Note: currently tests are not the most reliable - they work, but we need to account for a large amount of requests etc. so we should maybe add some retries directly in the code (separate PR)
=> BROC-490: Add acceptance tests for Code Change Source

CHANGELOG.md, internal/provider/resource_code_change_source.go
We were trying to import wrong indices when importing, which cause terraform to fail silently.
Fixes: https://github.com/sleuth-io/terraform-provider-sleuth/issues/133
=> TIE-261: Fix code_change_source import

CHANGELOG.md, docs/index.md, internal/gqlclient/environments.go, internal/provider/resource_environment.go, templates/index.md.tmpl
When we try to delete default env, we will get back the `Missing` error. Given that most time when deleting env, we will also delete project, we will swallow err for the time being and just remove env from the state.
To test:
- create a project and track a default `Production` environment
- delete an environment and project from the `main.tf`
```terraform
resource "sleuth_project" "terraform_test_deletion" {
name = "Terraform env testing deletion"
build_provider = "GITHUB"
}
resource "sleuth_environment" "prod_deletion" {
project_slug = sleuth_project.terraform_test_deletion.slug
name = "Production"
color = "#279694"
}
```
Results:
- before - error is returned
- after - successfully deleted
Resolves: https://github.com/sleuth-io/terraform-provider-sleuth/issues/136
=> TIE-242:  Ignore errors when deleting default env 

CHANGELOG.md, docs/resources/incident_impact_source.md, internal/provider/resource_incident_impact_source.go
Users were confused about what `remote_service` needed. They were supplying a service name, but it actually needs a service ID. This updates the docs to clarify that.
=> TIE-262: Update docs to clarify expected values

CHANGELOG.md, internal/gqlclient/change_sources.go, internal/gqlclient/code_change_sources.go
Currently repository & build provider is not uppercase when it is returned from the API but we expect it to be - fix it
=> TIE-274: Change provider value from API to uppercase

.devcontainer/devcontainer.json, CHANGELOG.md, docs/contributing/README.md, docs/resources/project.md, templates/contributing/README.md.tmpl
Aka `devcontainer.json` file so everyone else will get machine with
`go` and `terraform` preinstalled.
About 2 weeks ago, you could simply get terraform via `sudo apt update && sudo apt install terraform`, but now you can't anymore.
Now you need to follow many steps as described on [terraform docs](https://developer.hashicorp.com/terraform/tutorials/aws-get-started/install-cli), so I decided to add this `devcontainer` config instead.
=> WIP-324: Add .devcontainer config file for GitHub Codespaces

CHANGELOG.md
Last v0.4 release until new 0.5 version is released.
=> BROC-1198: Prepare v0.4.8 release

internal/sleuth/code_change_source_resource.go, main.tf.example
Two minor unrelated fixes, the actual fix is all in the `internal/sleuth/code_change_source_resource.go` file change.
=> SD-8511: TF provider crashes when creating a code deployment

CHANGELOG.md
~@nejcambrozic do you remember how to cut a new release?~ IIRC, pushing a new [tag](https://github.com/sleuth-io/terraform-provider-sleuth/tags) should do it all automatically? -> yes: https://github.com/sleuth-io/terraform-provider-sleuth/releases/tag/v0.6.1
[edit] also, flaky tests are annoying 😬
=> SD-8511: Add 0.6.1 to changelog

CHANGELOG.md, docs/resources/project.md, internal/gqlclient/models.go, internal/sleuth/project_resource.go
Depends on https://github.com/sleuth-io/sleuth/pull/10415
Allows you to specify project labels like so:
```tf
resource "sleuth_project" "terraform_poc" {
name = "Testing"
labels = ["terraform", "testing"]
}
```
I think acceptance tests are failing because we didn't deploy https://github.com/sleuth-io/sleuth/pull/10415 yet to prod or staging. I tried to run `make testacc` locally as described in https://github.com/sleuth-io/terraform-provider-sleuth/blob/ziga/fea-330-support-managing-project-labels-in-terraform/docs/contributing/README.md#testing but it errors out for me with
```
Error: API key must be set
```
but I have no idea where to set it since it's not documented :/
=> FEA-330: Add support setting labels on project creation

CHANGELOG.md, internal/sleuth/code_change_source_resource.go
It seems the repository.integration_slug causes errors if it's populated by a variable and used for multiple jobs.
This error does not happen on the build_mappings which use the same value. This PR just removes the state caching on the repo value to make it behave like the build mapping value
=> SD-8520: remove cached int_slug for repository

docs/index.md, internal/gqlclient/client.go, internal/sleuth/provider.go, templates/index.md.tmpl
The default timeout of 20 seconds appears to be insufficient in some cases (I encounter timeouts 100% of the time when applying impact source changes or creations). Making this configurable allows for accounting for these cases, and cases where users have slow or high-latency internet connections.
=> SD-8567: Add timeout field to provider

internal/gqlclient/models.go, internal/sleuth/code_change_source_resource.go
Resolves #200
When code integrations are configured in Sleuth in read-only mode, it is up to the user to manually add the relevant webhook to the relevant repository. These webhooks require secret tokens, which are only available in Sleuth after the code change source has been created.
This change allows a user of the Terraform provider to automatically create the webhooks in their code integration source. For example, with GitLab, it is possible to do:
```terraform
resource "sleuth_code_change_source" "example" {
}
resource "gitlab_project_hook" "example" {
project = "${sleuth_code_change_source.example.repository.owner}/${sleuth_code_change_source.example.repository.name}"
url     = sleuth_code_change_source.example.repository.webhook.url
token   = …
```
=> SD-8531: Expose repository webhook as computed attribute

CHANGELOG.md, docs/resources/code_change_source.md, internal/gqlclient/models.go, internal/sleuth/code_change_source_resource.go
https://linear.app/sleuth/issue/SD-8574/allow-marking-build-mappings-as-custom-via-tf-provider
=> SD-8574: Add support for `isCustom` attribute on build mappings

internal/gqlclient/code_change_sources.go
When a code change source managed by Terraform and tracked in Terraform state is deleted externally (e.g. by manually deleting it in the interface), the Terraform provider currently panics upon trying to apply without any Terraform changes:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc8 pc=0xab6e8b]
goroutine 2099 [running]:
github.com/sleuth-io/terraform-provider-sleuth/internal/sleuth.getNewStateFromCodeChangeSource({_, _}, _, {_, _}, {{0x2, {0xc001889900, 0x9}}, {0x2, {0xc0012b6a50, ...}}, ...})
github.com/sleuth-io/terraform-provider-sleuth/internal/sleuth/code_change_source_resource.go:497 +0x8b
github.com/sleuth-io/terraform-provider-sleuth/internal/sleuth.(*codeChangeSourceResource).Read(0xc00007 …
```
=> SD-8790: Fix panic when code deployment doesn't exist

.cursor/rules/code-source-project-name.md, docs/resources/code_change_source.md, internal/gqlclient/code_change_sources.go, internal/gqlclient/models.go, internal/sleuth/code_change_source_resource.go, internal/sleuth/code_change_source_resource_test.go
Instead of always requiring key, which is harder to get
=> SD-8778: Support setting azure build project name
