sleuth-io/terraform-provider-sleuth

CHANGELOG.md, internal/gqlclient/code_change_sources.go, internal/gqlclient/environments.go, internal/gqlclient/error_impact_sources.go, internal/gqlclient/metric_impact_sources.go, internal/gqlclient/projects.go, internal/provider/resource_code_change_source.go, internal/provider/resource_environment.go, internal/provider/resource_error_impact_source.go, internal/provider/resource_metric_impact_source.go, internal/provider/resource_project.go
If a resource was deleted in Sleuth, recreate
closes #21
=> Better handle missing entities

CHANGELOG.md, Makefile, docs/resources/code_change_source.md, internal/gqlclient/models.go, internal/provider/resource_code_change_source.go
* Exposed the ability to configure the integration slug
* Set the default of the new match parameter to true to match UI (and not graphql)
=> SD-7531 Expose the new match branch value

internal/gqlclient/metric_impact_sources.go, internal/provider/resource_metric_impact_source.go
Fixing metric impact source as mentioned in https://github.com/sleuth-io/terraform-provider-sleuth/pull/69
=> TIE-107: Fix metric impact source creation

.gitignore, CHANGELOG.md, Makefile, docs/contributing/README.md, internal/gqlclient/error_impact_sources.go, internal/gqlclient/metric_impact_sources.go, internal/provider/resource_error_impact_source.go, internal/provider/resource_metric_impact_source.go, main.tf.example
Best reviewed by commits where I explain / describe each change.
Metric impact source also looks broken, will fix it in next PR.
=> TIE-107: Fix error impact source creation

.gitignore, README.md, dev.tfrc.example, docs/contributing/README.md, templates/contributing/README.md.tmpl
Add local environment instructions.
=> BROC-381: Improve local env documentation

CHANGELOG.md, internal/gqlclient/incident_impact_source.go, internal/gqlclient/models.go, internal/provider/resource_incident_impact_source.go
This allows Terraform user to create a custom incident impact source
=> BROC-423: Allow custom incident impact source

CHANGELOG.md, internal/gqlclient/incident_impact_source.go
Adding logging consistency by translating Slovenian to English
=> BROC-427: Translate log message

CHANGELOG.md
Release latest changes to Terraform Registry
=> BROC-429: Release v0.4.1

docs/resources/project.md, internal/provider/provider.go, internal/sleuth/project_resource.go, internal/sleuth/provider.go
Rewrite Project resource 1:1 from old SDK to Framework.
=> BROC-261: Rewrite project resource to TF plugin framework

internal/sleuth/environment_resource_test.go
Add acceptance tests for new Env resource
=> BROC-513: Add acceptance tests for Environment resource

internal/sleuth/provider.go, internal/sleuth/provider_test.go, main.go
Add useragent string in HTTP client in new Framework SDK
=> BROC-524: Add useragent string in HTTP client in new Framework SDK

internal/gqlclient/models.go, internal/provider/provider.go, internal/provider/resource_metric_impact_source.go, internal/sleuth/metric_impact_source_resource.go, internal/sleuth/provider.go
Rewrite metric impact resource using Plugin SDK
=> BROC-263: Rewrite metric impact resource using Plugin SDK

internal/sleuth/metric_impact_source_resource_test.go
Add DataDog & CW acceptance test
=> BROC-514: Add metric impact source acceptance tests

internal/gqlclient/models.go, internal/provider/provider.go, internal/sleuth/error_impact_source_resource.go, internal/sleuth/provider.go
Rewrite Error impact source resource using Plugin SDK
=> BROC-264: Rewrite Error impact source resource using Plugin SDK

docs/resources/incident_impact_source.md, examples/resources/sleuth_incident_impact_source/resource.tf, internal/gqlclient/models.go, internal/provider/resource_incident_impact_source.go
With this you can add Statuspage as an impact source
=> BROC-436: Add Statuspage as a provider

CHANGELOG.md
Release v0.4.3 of Sleuth Terraform provider
=> BROC-576: Release v0.4.3

CHANGELOG.md
New release for reported 2 issues
=> BROC-665: Prepare v0.4.4 release

CHANGELOG.md
=> BROC-674: Prepare 0.4.5 release

CHANGELOG.md, internal/gqlclient/models.go, internal/provider/resource_project.go
Add CLT specific fields inside TF provider
=> TDD-692: Add CLT project settings to project resource

CHANGELOG.md
=> BROC-744: Release v0.4.6

CHANGELOG.md, docs/resources/code_change_source.md, internal/provider/resource_code_change_source.go
We should force the order of build_mappings
=> TIE-289: Update documentation about build_mappings order

CHANGELOG.md
=> BROC-789: Release v0.4.7

internal/gqlclient/models.go, internal/gqlclient/projects.go, internal/provider/provider.go, internal/provider/resource_incident_impact_source.go, internal/sleuth/environment_resource.go, internal/sleuth/incident_impact_source_resource.go, internal/sleuth/incident_impact_source_resource_test.go, internal/sleuth/provider.go, main.go
Rewrite Impacts using Framework SDK
=> BROC-515: Rewrite Incident impact source using Framework SDK

.github/workflows/test.yml, internal/sleuth/code_change_source_resource.go, internal/sleuth/code_change_source_resource_test.go
Was already merged into release-0.5-prepare branch but a bad merge removed this PR - reapply it
=> BROC-490: Add code change source acceptance tests

CHANGELOG.md, main.go
To enable debugging we need to have the correct name inside main so debugger will actually connect.
=> SD-8423: Fix provider name in main function

internal/provider/resource_project.go, internal/sleuth/project_resource.go
=> SD-8184: Port CLT changes from 0.4

.github/workflows/release.yml, .github/workflows/test.yml, CHANGELOG.md
Take new tooling from scaffold to be up to date
=> SD-8428: Update Github actions tooling

CHANGELOG.md, docs/index.md, docs/resources/code_change_source.md, docs/resources/environment.md, docs/resources/error_impact_source.md, docs/resources/incident_impact_source.md, docs/resources/metric_impact_source.md, docs/resources/project.md, examples/resources/sleuth_code_change_source/resource.tf, examples/resources/sleuth_environment/resource.tf, examples/resources/sleuth_error_impact_source/resource.tf, examples/resources/sleuth_metric_impact_source/resource.tf, internal/sleuth/environment_resource.go, internal/sleuth/incident_impact_source_resource.go, internal/sleuth/metric_impact_source_resource.go, templates/index.md.tmpl
Explain versions & update docs + re-generate
=> SD-8429: Update documentation and explain versions

CHANGELOG.md
=> BROC-1199: Prepare v0.5.1 release

CHANGELOG.md
This is the changelog for the 0.6.0 release
=> SD-8430: adds 0.6.0 to changelog

internal/sleuth/code_change_source_resource.go
When trying to import a `sleuth_code_change_source`, the Terraform provider currently panics:
```
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the
│ plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
Stack trace from the terraform-provider-sleuth_v0.6.2 plugin:
panic: runtime error: index out of range [1] with length 1
goroutine 44 [running]:
github.com/sleuth-io/terraform-provider-sleuth/internal/sleuth.(*codeChangeSourceResource).Read(0xc000500018, {0xd92d08?, 0xc000530ed0?}, {{{{0xd97990, 0xc00035b320}, {0xb64200, 0xc00035b1a0}}, {0xd998a8, 0xc0000b3090}}, 0xc0006bc018, ...}, ...)                                           github.com/sleuth-io/terraform-provider-sleuth/internal/sleuth/code_change_sou …
```
=> SD-8526: Improve code change source import error handling

CHANGELOG.md
just updating the changelog for release
=> SD-8526: update changelog for 0.6.4 release

docs/resources/code_change_source.md
Forgot to run `make docs` command.
=> SD-8531: Update docs

CHANGELOG.md
=> SD-8572: update changelog for 0.6.7
